# Generated by Django 3.2.9 on 2022-02-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['is_complete', 'priority', 'begin']},
        ),
    ]
