# Generated by Django 3.2.9 on 2022-02-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'priority', 'begin']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='The technician who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created', to='prosdib.technician', verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not assigned'), (1, 'In progress'), (2, 'Paused'), (3, 'Canceled'), (4, 'Completed')], default=1, help_text='The status of the project', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the project', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, '1) Solve a Safety Hazard or Work Stoppage'), (2, '2) Fix a Major Problem or Implement a Major Improvement'), (3, '3) Fix a Highly Important Issue or Implement an Important Solution'), (4, '4) Fix a Moderately Important Issue or Implement a Moderately Importent Solution'), (5, '5) Fix a Minor Issue or implement a minor improvement')], default=4, help_text='The priority, on a scale of 1 to 5, where 1 is the highest priority', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='The technician primarily responsible for executing this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_responsibility', to='prosdib.technician', verbose_name='technician'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='A short description of the project', max_length=75, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='submitted_by',
            field=models.ForeignKey(help_text='The technician who submitted this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prosdib.technician', verbose_name='submitted by'),
        ),
    ]
