# Generated by Django 3.2.9 on 2022-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0004_auto_20220218_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnote',
            name='is_major',
        ),
        migrations.AddField(
            model_name='projectnote',
            name='is_current',
            field=models.BooleanField(default=False, help_text='If this note is diplayed by default in the project detail view.  If not, it will be displayed when "Show All" is selected', verbose_name='is current status'),
        ),
    ]
