# Generated by Django 3.2.9 on 2022-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0005_auto_20220220_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnote',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of time to be added to the project as per this note.  Use decimal notation (ex 1.25, not 1:15)', max_digits=6, verbose_name='time spent'),
        ),
    ]
