# Generated by Django 3.2.9 on 2022-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0006_alter_projectnote_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of time to be added to the project in addition to time spent logged in notes.  Use decimal notation (ex 1.25, not 1:15)', max_digits=6, verbose_name='time spent'),
        ),
    ]
