# Generated by Django 3.2.9 on 2022-03-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0007_project_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnote',
            options={'ordering': ['-when']},
        ),
    ]
