# Generated by Django 3.2.9 on 2022-05-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0008_alter_projectnote_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the technician', max_length=50, verbose_name='name')),
                ('list_position', models.IntegerField(default=10000, help_text='The position of this status in a list, not sorted by other fields', verbose_name='list position')),
                ('is_active', models.BooleanField(default=True, help_text='If this status means the project is active ', verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, help_text='If this status is the default for new projects.  Only one should be chosen', verbose_name='default')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status_new',
            field=models.ForeignKey(help_text='The status of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prosdib.status', verbose_name='status'),
        ),
    ]
