# Generated by Django 3.2.9 on 2022-05-05 11:11

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations

def forwards_func(apps, schema_editor):
    Status = apps.get_model("prosdib", "Status")
    Project = apps.get_model("prosdib", "Project")
    db_alias = schema_editor.connection.alias
    for project in Project.objects.using(db_alias).all():
        status, created = Status.objects.get_or_create(
            name=project.get_status_display()
        )
        project.status_new = status
        project.save()

    for status_choice in Project.STATUS_CHOICES:
        status, created = Status.objects.get_or_create(
            name = status_choice[1]
        )

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Status instances,
    # so reverse_func() should delete them.
    Status = apps.get_model("prosdib", "Status")
    db_alias = schema_editor.connection.alias
    Status.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0009_auto_20220505_0711'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
