# Generated by Django 3.2.9 on 2022-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0010_transfer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status_old', 'priority', 'begin']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='status_old',
        ),
    ]
