# Generated by Django 3.2.9 on 2022-05-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0011_auto_20220514_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'priority', 'begin']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='status_new',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status_old',
        ),
    ]
