# Generated by Django 3.2.9 on 2022-05-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0012_auto_20220514_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('list_position', 'name')},
        ),
    ]
