# Generated by Django 3.2.9 on 2022-05-26 10:43

from django.db import migrations, models
import django.db.models.deletion
import prosdib.models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0014_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=prosdib.models.get_default_status, help_text='The status of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prosdib.status', verbose_name='status'),
        ),
    ]
