# Generated by Django 4.1.2 on 2023-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0015_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'priority']},
        ),
        migrations.AddField(
            model_name='projectnote',
            name='details',
            field=models.TextField(blank=True, help_text='The details of the note if the summary text is not sufficient', verbose_name='details'),
        ),
    ]
