# Generated by Django 4.1.2 on 2023-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0016_alter_project_options_projectnote_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnote',
            old_name='text',
            new_name='maintext',
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='details',
            field=models.TextField(blank=True, help_text='The details of the note if the main text is not sufficient', verbose_name='details'),
        ),
    ]
