# Generated by Django 4.1.2 on 2023-01-25 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosdib', '0018_remove_project_completion_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='begin',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the project was submitted'),
        ),
    ]
